package com.javaCore;

import java.util.Scanner;

public class CustomException {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter your age:");
        int age = sc.nextInt();

        try {
            System.out.println("Hi");
            if (age >= 18) {
                System.out.println("You are eligible to vote.");
            } else {
                // Here you throw the custom exception
                throw new UnderAge("You are under age."); 
            }
        } catch (UnderAge e) {
            // When exception is thrown, it's caught here
            System.out.println("Hello");
            System.out.println(e.getMessage()); // This will print the exception message
        }
    }
}

class UnderAge extends RuntimeException {

    public UnderAge(String msg) {
        super(msg); // Pass the message to the RuntimeException constructor
    }
}